name: phferreira
description: Portfolio project
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.1.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
  fonts:
    - family: Pacifico
      fonts: 
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: RobotoMono
      fonts: 
        - asset: assets/fonts/Roboto Mono Medium Nerd Font Complete Mono.ttf
